/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EIOSGAMECENTER_AUTODEFS_H
#define S3EIOSGAMECENTER_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_IOSGAMECENTER_NAME "s3eIOSGameCenter"
#define S3E_EXT_IOSGAMECENTER_HASH 0x79dc6b96

#endif /* !S3EIOSGAMECENTER_AUTODEFS_H */
